# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

parameters:
- name: "testplan"
  type: string
  default: "default_value"

- name: "USER"
  type: string
  default: "default_value"

variables:
- name: USER
  value: initialValue

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, ${{ parameters.testplan }}!
  displayName: 'Run a one-line script'

- script: echo Hello, ${{ parameters.USER}}!
  displayName: 'Run a one-line script'

- script: echo Hello, ${{ variables.USER}}!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
